# Generated by Django 4.2.7 on 2025-06-24 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FraudTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_date_trans_time', models.DateTimeField()),
                ('category', models.CharField(max_length=50)),
                ('amount_inr', models.FloatField()),
                ('sender_city', models.CharField(max_length=100)),
                ('receiver_city', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('has_previous_transaction', models.BooleanField(default=False)),
                ('previous_transaction_date', models.DateTimeField(blank=True, null=True)),
                ('distance_km', models.FloatField()),
                ('city_pop', models.IntegerField()),
                ('age', models.IntegerField()),
                ('hour', models.IntegerField()),
                ('weekday', models.IntegerField()),
                ('day', models.IntegerField()),
                ('month', models.IntegerField()),
                ('is_night', models.BooleanField()),
                ('secs_since_last', models.FloatField(default=0)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('device', models.CharField(blank=True, max_length=100)),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('merchant_id', models.CharField(blank=True, max_length=100)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('risk_score', models.FloatField()),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('declined', 'Declined'), ('pending', 'Pending')], max_length=20)),
                ('recommendation', models.CharField(choices=[('approve', 'Approve'), ('decline', 'Decline'), ('review', 'Review')], max_length=20)),
                ('fraud_probability', models.FloatField()),
                ('confidence_score', models.FloatField()),
                ('processing_time', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
